filebeat:
  prospectors:
    -
      paths:
        - /var/log/linkshare.log
      input_type: log
      ignore_older: 720h
      document_type: linksharelogs
      scan_frequency: 5s
      multiline:
        pattern: ^[0-9]
        negate: true
        match: after
        max_lines: 500
        timeout: 5s

output:
  logstash:
    hosts: ["localhost:4000"]
    worker: 1

shipper:
logging:
  to_files: true
  files:
    path: /var/log
    name: linksharelogs
    rotateeverybytes: 6574578
  level: info
