version: '3'

services:
  linkshare:
    container_name: LinkShare
    build:
      dockerfile: docker/
      context: ../
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    container_name: LSRedis
    image: redis:latest
    networks:
      - appnet

networks:
  appnet: