version: '3'

services:
  LinkShare:
    container_name: LinkShare
    image: linkshare:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    container_name: LSRedis
    image: redis:latest
    ports:
      - 6379:6379